// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8-UWvdD6Oy4mvXSuNBoy_DV3Z6BcnHcs',
    appId: '1:590818736381:web:934072a32f5f692d972694',
    messagingSenderId: '590818736381',
    projectId: 'therhappy-7bb65',
    authDomain: 'therhappy-7bb65.firebaseapp.com',
    databaseURL:
        'https://therhappy-7bb65-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'therhappy-7bb65.appspot.com',
    measurementId: 'G-NW27FDGQJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGxtLumLREufq5fGLipwzn5TheYlLq8MI',
    appId: '1:590818736381:android:66640a79f219873e972694',
    messagingSenderId: '590818736381',
    projectId: 'therhappy-7bb65',
    databaseURL:
        'https://therhappy-7bb65-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'therhappy-7bb65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLijElAbSosCueRhrjn7s5cTwZ_sQLL_E',
    appId: '1:590818736381:ios:75056ee82c4b9694972694',
    messagingSenderId: '590818736381',
    projectId: 'therhappy-7bb65',
    databaseURL:
        'https://therhappy-7bb65-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'therhappy-7bb65.appspot.com',
    iosBundleId: 'com.example.therhappy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLijElAbSosCueRhrjn7s5cTwZ_sQLL_E',
    appId: '1:590818736381:ios:a1276e56916963ee972694',
    messagingSenderId: '590818736381',
    projectId: 'therhappy-7bb65',
    databaseURL:
        'https://therhappy-7bb65-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'therhappy-7bb65.appspot.com',
    iosBundleId: 'com.example.therhappy.RunnerTests',
  );
}
